export const ROUTES = {
  NOW_PLAYING_MOVIES_TAB: 'NOW PLAYING',
  POPULAR_MOVIES_TAB: 'POPULAR',
  TOP_RATED_MOVIES_TAB: 'TOP RATED',
  UPCOMING_MOVIES_TAB: 'UPCOMING',
};

export const SCREENS = {
  TAB_SCREEN: 'TAB SCREEN',
  MOVIE_ITEM_SCREEN: 'MOVIE ITEM SCREEN',
};
